name: release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Test
        run: make test
      - uses: AutoModality/action-clean@v1
      - name: sleep 10 sec
        run: sleep 10
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: release
        uses: anothrNick/github-tag-action@1.35.0
        env:
          INITIAL_VERSION: 0.0.0
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
      - name: Bump Version
        run: |
          echo "${{ steps.release.outputs.tag }}" > VERSION
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add VERSION
          git commit -m "bump version"
          git push
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rafaelcalleja/docker-container-installer:${{ steps.release.outputs.tag }}